public class BinarySearchTester {
    public static void main(String[] args) {
        MyBST<Integer> binarySearchTree = new MyBST<Integer>();
        // MyBST<String> binarySearchTree = new MyBST<String>();
     
        // binarySearchTree.add("c");
        // binarySearchTree.add("b");
        // binarySearchTree.add("a");
      
        binarySearchTree.add(9);
        binarySearchTree.add(49);
        binarySearchTree.add(41);
        binarySearchTree.add(42);
        binarySearchTree.add(55);
        binarySearchTree.add(67);
        binarySearchTree.add(63);
        binarySearchTree.add(61);
        binarySearchTree.add(50);
        binarySearchTree.add(77);
        binarySearchTree.add(77);
        binarySearchTree.add(48);
        binarySearchTree.add(36);
        binarySearchTree.add(49);
        binarySearchTree.add(92);
        binarySearchTree.add(78);
        binarySearchTree.add(58);
        binarySearchTree.add(67);
        binarySearchTree.add(5);
        binarySearchTree.add(43);
        binarySearchTree.add(0);
        binarySearchTree.add(14);
        binarySearchTree.add(46);
        binarySearchTree.add(57);
        binarySearchTree.add(94);
        binarySearchTree.add(46);
        binarySearchTree.add(87);
        binarySearchTree.add(79);
        binarySearchTree.add(71);
        binarySearchTree.add(42);
        binarySearchTree.add(35);
        binarySearchTree.add(37);
        binarySearchTree.add(52);
        binarySearchTree.add(63);
        binarySearchTree.add(46);
        binarySearchTree.add(75);
        binarySearchTree.add(92);
        binarySearchTree.add(26);
        binarySearchTree.add(34);
        binarySearchTree.add(76);
        binarySearchTree.add(94);
        binarySearchTree.add(21);
        binarySearchTree.add(58);
        binarySearchTree.add(92);
        binarySearchTree.add(7);
        binarySearchTree.add(80);
        binarySearchTree.add(36);
        binarySearchTree.add(66);
        binarySearchTree.add(0);
        binarySearchTree.add(41);
        binarySearchTree.add(29);
        binarySearchTree.add(95);
        binarySearchTree.add(96);
        binarySearchTree.add(88);
        binarySearchTree.add(58);
        binarySearchTree.add(57);
        binarySearchTree.add(18);
        binarySearchTree.add(28);
        binarySearchTree.add(18);
        binarySearchTree.add(60);
        binarySearchTree.add(15);
        binarySearchTree.add(71);
        binarySearchTree.add(39);
        binarySearchTree.add(40);
        binarySearchTree.add(68);
        binarySearchTree.add(75);
        binarySearchTree.add(29);
        binarySearchTree.add(16);
        binarySearchTree.add(28);
        binarySearchTree.add(94);
        binarySearchTree.add(11);
        binarySearchTree.add(24);
        binarySearchTree.add(23);
        binarySearchTree.add(97);
        binarySearchTree.add(9);
        binarySearchTree.add(31);
        binarySearchTree.add(75);
        binarySearchTree.add(80);
        binarySearchTree.add(33);
        binarySearchTree.add(0);
        binarySearchTree.add(78);
        binarySearchTree.add(0);
        binarySearchTree.add(3);
        binarySearchTree.add(94);
        binarySearchTree.add(90);
        binarySearchTree.add(71);
        binarySearchTree.add(27);
        binarySearchTree.add(77);
        binarySearchTree.add(94);
        binarySearchTree.add(13);
        binarySearchTree.add(69);
        binarySearchTree.add(49);
        binarySearchTree.add(51);
        binarySearchTree.add(48);
        binarySearchTree.add(38);
        binarySearchTree.add(31);
        binarySearchTree.add(53);
        binarySearchTree.add(60);
        binarySearchTree.add(51);
        binarySearchTree.add(60);
        System.out.println(binarySearchTree.toString());
        System.out.println(binarySearchTree.remove(41));
        System.out.println(binarySearchTree.toString());
        // // System.out.println(binarySearchTree.toString());
        // // System.out.println("3");
        // System.out.println(binarySearchTree.toString());
        // System.out.println(binarySearchTree.remove("c"));
        // System.out.println(binarySearchTree.toString());
        // System.out.println("contains a?: " + binarySearchTree.contains("a"));


        // for (int i = 0; i < 100; i++) {
        //     int a = (int) ( Math.random() * 99);
        //     System.out.println("binarySearchTree.add(" + a + ");");
        // }

    }
}
